version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  app:
    build: ./
    environment:
      - MONGO_URI=mongodb://mongo:27017/catalog
    ports:
      - 8080:8080  
    depends_on:
      - mongo
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  mongo-data:
  caddy_data:
  caddy_config:


 
