version: '3.8'

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  app:
    build: ./
    environment:
      - MONGO_URI=mongodb://mongo:27017/catalog
    ports:
      - "3000:8080"  # External port 3000 maps to internal 5000
    depends_on:
      - mongo
    restart: unless-stopped

  caddy:
    image: caddy
    ports:
      - "80:80"  # Expose HTTP on port 80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
    restart: unless-stopped

volumes:
  mongo-data:
